import BackgroundSVG from "../public/background-stars.svg";
import type { Metadata } from "next";
import Image from "next/image";
import "../sass/index.scss";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Planets Fact Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const { width } = useWindowSize();

  return (
    <html lang="en">
      <body>
        <header className="between">
          <h1>The Planets</h1>
          <Navigation />
        </header>
        {children}
        <Image className="global-background" src={BackgroundSVG} alt="background of start" width={0} height={0} sizes="100vw" style={{ height: "100%", objectFit: "cover" }} />
      </body>
    </html>
  );
}
