import BackgroundSVG from "../public/background-stars.svg";
import type { Metadata } from "next";
import Image from "next/image";
import "../sass/index.scss";

export const metadata: Metadata = {
  title: "Planets Fact Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const { width } = useWindowSize();

  return (
    <html lang="en">
      <body>
        <header>
          <h1>The Planets</h1>
          {/* {width! > 768 && (
            <nav>
              <ul>
                <li>Mercury</li>
                <li>Venus</li>
                <li>Earth</li>
                <li>Mars</li>
                <li>Jupiter</li>
                <li>Saturn</li>
                <li>Uranus</li>
                <li>Neptune</li>
              </ul>
            </nav>
          )} */}
          <Image src={"/icon-hamburger.svg"} alt="menu icon" height={24} width={24} />
        </header>
        {children}
        <Image className="global-background" src={BackgroundSVG} alt="background of start" width={0} height={0} sizes="100vw" style={{ height: "100%", objectFit: "cover" }} />
      </body>
    </html>
  );
}
